### ISSUE TITLE
About the release time of the code

### ISSUE THREAD

**Issue by pzw1231** [kaize0409/HyperGAT#1]
Your paper is very good.  I want to reproduce the experiment in your paper. When do you expose the code?

**Comment by a773938364** [comment]
I want to ask this question, too

**Comment by Jackson117** [comment]
Hey, I have read about your paper and tried to reproduce the model on hypergraph node classification job. However, I got quite poor performance. Actually, the model's loss could not decend at all. When could you release your code so that I can figure out what the problem is?

**Comment by kaize0409** [comment]
Please check out our released code, thank you!
