### ISSUE TITLE
How to generate LDA?

### ISSUE THREAD

**Issue by kaohaochuan** [kaize0409/HyperGAT#3]
Thanks your work!
I want to implement on my own Chinese data.
May I asked how to generate LDA.p data?
I have generate tcorpus and label.
Thanks!

**Comment by kaohaochuan** [comment]
@kaize0409  I saw that you have uploaded generate_LDA.py file!
I will try it soon!
Thanks you!You guys amazing!

**Comment by kaize0409** [comment]
It's our pleasure! Hope it can help your research.

> @kaize0409 I saw that you have uploaded generatw_LDA.py file!
> I will try it soon!
> Thanks you!You guys amazing!

**Comment by lockingkao** [comment]
> It's our pleasure! Hope it can help your research.
> 
> > @kaize0409 I saw that you have uploaded generatw_LDA.py file!
> > I will try it soon!
> > Thanks you!You guys amazing!
Hello !
I can use the   generate_LDA.py    now!
But I still have something confused!
`parser.add_argument('--topn', type=int, default=10, help='top n keywords')
parser.add_argument('--topics', type=int, help='number of topics')`

I know` --topn `is like your paper mention that top K words right?
But How to determine the number of  `--topics` ?
The number of labels?   
like R8 has  `--topics :8` R52 has `--topics :52`
I'm nor really sure:(

**Comment by lockingkao** [comment]
Also I am trying to modify the framework of work to fit on my Chinese multi label text classification data.
Which have approximately 2500 text with 9 labels.
Have you ever try your HyperGAT on multi label classification tesk?
such like KAGGLE's _toxic comment classification dataset_  ?
