### ISSUE TITLE
Remaining Datasets

### ISSUE THREAD

**Issue by shamnastv** [kaize0409/HyperGAT#6]
Thank you for this code.

Could you please provide the remaining datasets(20ng, ohsumed, and MR). or the link to datasets with preprocessing script.

Thanks

**Comment by yangyt-2020** [comment]
Hello, first of all thank you for your work. I want to reproduce the results of the paper on other datasets（20ng, ohsumed, and MR）. Could you please share the remaining datasets？My email address is “yangyt20@mails.jlu.edu.cn”. Thanks again!

**Comment by wangjlgz** [comment]
For all the public datasets, you can download them from https://github.com/yao8839836/text_gcn/tree/master/data/corpus. You will need to run the preprocessing script ‘generate_lda.py' to obtain the LDA-related files.
